version: "3.5"
services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql  
        environment:
            MYSQL_ROOT_PASSWORD: test        
        volumes:
            - ./test-schema/db/:/docker-entrypoint-initdb.d/:ro
        ports:
            - 3306:3306
        networks:
            - my-network

    db-ref:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        container_name: mysql-ref  
        environment:
            MYSQL_ROOT_PASSWORD: test        
        volumes:
            - ./test-schema/db/:/docker-entrypoint-initdb.d/:ro
        ports:
            - 3307:3306
        networks:
            - new-network

    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports: 
            - 8080:8080
        networks:
            - my-network        

networks:
    my-network:
        driver: bridge
    new-network:
        driver: bridge
